export const FETCH_REMAINING_BUDGET = "FETCH_REMAINING_BUDGET";
export const FETCH_ITEMS = "FETCH_ITEMS";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const DECREMENT_REMAINING = "DECREMENT_REMAINING";
